-- 코드를 입력하세요
SELECT C.CAR_ID as CAR_ID , C.CAR_TYPE as CAR_TYPE, 
    (ROUND((100-DISCOUNT_RATE)/100*C.DAILY_FEE*30, 0)) as FEE
FROM CAR_RENTAL_COMPANY_CAR as C 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as D
ON C.CAR_TYPE = D.CAR_TYPE AND DURATION_TYPE='30일 이상'
WHERE (C.CAR_TYPE='세단' OR C.CAR_TYPE='SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID 
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                     WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
HAVING FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID;