-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) as YEAR, MONTH(O.SALES_DATE) as MONTH, COUNT(DISTINCT O.USER_ID) as PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1) as PURCHASED_RATIO
-- SELECT *
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
AND YEAR(U.JOINED)=2021
GROUP BY DATE_FORMAT(O.SALES_DATE, '%Y-%m')
ORDER BY YEAR, MONTH;