-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(CAR_ID)as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE between '2022-08-01' and '2022-10-31'
and CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                where START_DATE between '2022-08-01' and '2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID)>=5)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(CAR_ID)>0
ORDER BY MONTH, CAR_ID DESC



