-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', f.BOARD_ID , '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD b
LEFT OUTER JOIN USED_GOODS_FILE f
ON b.BOARD_ID = f.BOARD_ID
WHERE b.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC;