-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m, REST_REVIEW r
WHERE m.MEMBER_ID=r.MEMBER_ID
AND m.MEMBER_ID IN(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT MAX(review) FROM (SELECT COUNT(*) as review FROM REST_REVIEW GROUP BY MEMBER_ID) as result))
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT;