SELECT DISTINCT h.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
LEFT JOIN CAR_RENTAL_COMPANY_CAR as c
ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE='세단' and h.START_DATE between '2022-10-01' and '2022-10-30'
ORDER BY CAR_ID DESC